project:
  type: website
  output-dir: docs

website:
  title: "Northeast US Marine Species Distribution Shifts"
  site-url: https://carlylovas.github.io/species.shifts/

  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Articles"
        menu:
          - text: "Accessing and cleaning federal fisheries data"
            href: articles/data_cleaning_functions.qmd
          - text: "Plotting federal fisheries data"
            href: articles/plotting_functions.qmd
      - text: "Reference"
        href: reference/index.qmd
    right:
      - icon: github
        href: https://github.com/carlylovas/species.shifts

format:
  html:
    theme: cosmo
    toc: true
