project:
  type: website
  output-dir: _output

format:
  html:
    theme: cosmo
    toc: true
    embed-resources: false

website:
  title: "Species distribution shifts"
  navbar:
    left:
      - href: README.Rmd
